import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { GTAOPass } from 'three/addons/postprocessing/GTAOPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { FXAAShader } from 'three/addons/shaders/FXAAShader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import type { Collider, InteractiveTarget, StoreRecord } from './experience/types';
import { SimplexNoise } from 'three/addons/math/SimplexNoise.js';
import { rng } from './art';

import { applyArchitectureProbe } from './architecture';
import { Pass } from 'three/addons/postprocessing/Pass.js';

export interface World { group:THREE.Group; groundHeight:(x:number,z:number,previousFeetY?:number)=>number; colliders:Collider[]; update:(t:number,dt:number)=>void; targets?:InteractiveTarget[];stores?:StoreRecord[];setLighting?:(mode:string)=>void;reset?:()=>void;updateViewer?:(position:THREE.Vector3)=>void }
type Mode='walk'|'free'|'orbit'|'tour'; type Debug='none'|'gtao'|'normal';
interface View { id:string; label:string; position:[number,number,number]; target:[number,number,number]; mode:Mode;fov?:number }
export const cameras:View[]=[
  {id:'overview',label:'01 · The whole square',position:[83,95,76],target:[0,10,0],mode:'free'},
  {id:'monument',label:'02 · Dewey Monument',position:[14,4.1,12],target:[0,17,0],mode:'walk'},
  {id:'westin',label:'03 · Powell & the St. Francis',position:[12,4.1,3],target:[-85,24,0],mode:'walk'},
  {id:'north',label:'04 · Across the north terrace',position:[-8,4.1,-25],target:[25,5,18],mode:'walk'},
  {id:'south',label:'05 · Geary Street approach',position:[0,2.5,46],target:[0,13,-16],mode:'walk'},
  {id:'corner',label:'06 · Powell & Geary corner',position:[-68,2.2,45],target:[-22,13,-20],mode:'walk'},
  {id:'stockton',label:'07 · Stockton Street',position:[68,2.5,-36],target:[0,9,-12],mode:'walk'},
  {id:'detail',label:'08 · A seat in the square',position:[-22.5,2.9,30.5],target:[-20,1.8,28.7],mode:'walk'},
  {id:'victory',label:'09 · Victory above the square',position:[3.5,32.2,5.8],target:[0,30.7,0],mode:'free'},
  {id:'stone',label:'10 · Monument stonework',position:[4.5,4.1,7],target:[0,4.8,0],mode:'walk'},
  {id:'west-cafe',label:'11 · West cafe pavilion',position:[-40,4.1,7],target:[-51,4.3,8],mode:'walk'},
  {id:'northwest',label:'12 · Powell & Post corner',position:[-67,5,-44],target:[3,12,4],mode:'walk'},
  {id:'northeast',label:'13 · Post & Stockton corner',position:[67,5,-44],target:[-5,12,5],mode:'walk'},
  {id:'southeast',label:'14 · Stockton & Geary corner',position:[67,2.4,44],target:[-5,12,-5],mode:'walk'},
  {id:'center-north',label:'15 · Plaza facing Post Street',position:[8,4.1,5],target:[8,12,-70],mode:'walk'},
  {id:'center-east',label:'16 · Plaza facing Stockton Street',position:[8,4.1,5],target:[90,12,5],mode:'walk'},
  {id:'center-south',label:'17 · Plaza facing Geary Street',position:[8,4.1,5],target:[8,12,75],mode:'walk'},
  {id:'center-west',label:'18 · Plaza facing Powell Street',position:[8,4.1,5],target:[-90,20,5],mode:'walk'},
  {id:'apple-front',label:'19 · Apple Union Square entrance',position:[44.1,5.3,-58],target:[44.1,10,-70],mode:'walk'},
  {id:'apple-ground',label:'20 · Apple ground floor',position:[44.1,5.5357,-66.5],target:[44.1,7,-83],mode:'walk'},
  {id:'apple-upper',label:'21 · Apple upper floor',position:[44.1,10.0357,-76.8],target:[44.1,11.54,-85.75],mode:'walk'},
  {id:'nintendo-front',label:'22 · Nintendo Powell Street entrance',position:[-81,2.851,32],target:[-92,5.4,32],mode:'walk'},
  {id:'nintendo-ground',label:'23 · Nintendo ground floor',position:[-88.8,2.851,32],target:[-95,2.55,32],mode:'walk'},
  {id:'nintendo-lower',label:'24 · Nintendo lower floor',position:[-97,-.749,28.7],target:[-100.9,-.449,32],mode:'walk'}
];
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const initialTime=performance.now();

export async function createRuntime(builder:()=>Promise<World>){
  const errors:Array<{kind:string,message:string,time:number}>=[];
  const record=(kind:string,error:unknown)=>errors.push({kind,message:String(error),time:performance.now()});
  const originalConsoleError=console.error;const captureConsoleError=(...values:unknown[])=>{record('console',values.map(v=>v instanceof Error?v.stack:String(v)).join(' '));originalConsoleError(...values);};console.error=captureConsoleError;
  window.addEventListener('error',e=>record('runtime',e.message));
  window.addEventListener('unhandledrejection',e=>record('rejection',e.reason));
  THREE.DefaultLoadingManager.onError=url=>record('asset',url);THREE.DefaultLoadingManager.onProgress=(_url,loaded,total)=>{$('loading-detail').textContent=`Loading local assets · ${loaded} of ${total}`;};
  const state={status:'initializing',stage:'renderer setup',mode:'free' as Mode,view:'overview',light:'day',quality:'high',frozen:false,focusedTarget:null as string|null,focusedStore:null as string|null,selectedStore:null as string|null,seated:null as string|null,referenceOpen:false,tourStop:null as string|null,features:{gtao:true},debug:'none' as Debug,time:0,disposed:false};
  const scene=new THREE.Scene(); scene.background=new THREE.Color('#bfd4e4'); scene.fog=new THREE.Fog('#ccd9df',260,850);
  const camera=new THREE.PerspectiveCamera(55,1,.15,1600); camera.rotation.order='YXZ';
  const renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});
  renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.03;
  renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true; renderer.shadowMap.type=THREE.PCFShadowMap; renderer.info.autoReset=false;
  renderer.debug.onShaderError=(gl,program,vs,fs)=>record('shader',[gl.getProgramInfoLog(program),gl.getShaderInfoLog(vs),gl.getShaderInfoLog(fs)].join('\n'));
  renderer.domElement.tabIndex=0; $('viewport').appendChild(renderer.domElement);
  const orbit=new OrbitControls(camera,renderer.domElement);orbit.enabled=false;orbit.enableDamping=true;orbit.dampingFactor=.08;orbit.minDistance=2;orbit.maxDistance=450;orbit.maxPolarAngle=Math.PI*.495;orbit.target.set(0,5,0);
  const focusBox=new THREE.Box3();const focusHighlight=new THREE.Box3Helper(focusBox,0xbdd7a0);focusHighlight.name='Interaction focus UI';focusHighlight.visible=false;const focusMaterial=focusHighlight.material as THREE.LineBasicMaterial;focusMaterial.transparent=true;focusMaterial.opacity=.55;focusMaterial.depthTest=false;scene.add(focusHighlight);
  renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();record('webgl','Context lost');state.status='error';showError('The graphics context was lost. Reload to recover.');});
  const skyMaterial=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{sunStrength:{value:1},sunDirection:{value:new THREE.Vector3(-.45,.75,.4)},zenith:{value:new THREE.Color('#6aafe1')},horizon:{value:new THREE.Color('#dce6e9')}},vertexShader:'varying vec3 direction;void main(){direction=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 direction;uniform float sunStrength;uniform vec3 sunDirection;uniform vec3 zenith;uniform vec3 horizon;void main(){vec3 d=normalize(direction);float h=pow(max(d.y,0.),.45);vec3 c=mix(horizon,zenith,h);float sun=max(dot(d,sunDirection),0.);c+=vec3(1.,.86,.63)*pow(sun,200.)*.18*sunStrength;c+=vec3(8.,7.,5.)*smoothstep(.99988,.99996,sun)*sunStrength;gl_FragColor=vec4(c,1.);}'});
  const sky=new THREE.Mesh(new THREE.SphereGeometry(1100,32,16),skyMaterial);sky.name='Procedural clear San Francisco sky';scene.add(sky);
  const sun=new THREE.DirectionalLight('#fff5db',3.3); sun.position.set(-90,145,75); sun.castShadow=true;
  sun.shadow.mapSize.set(4096,4096); const sc=sun.shadow.camera; sc.left=-145;sc.right=145;sc.top=145;sc.bottom=-145;sc.near=1;sc.far=430;sun.shadow.bias=-.00015;sun.shadow.normalBias=.1;sun.shadow.radius=2;
  scene.add(sun,sun.target); const hemi=new THREE.HemisphereLight('#cde7ff','#8f897a',1.6);scene.add(hemi);
  const pmrem=new THREE.PMREMGenerator(renderer);let environment:THREE.WebGLRenderTarget|undefined;let disposeArchitectureProbe:(()=>void)|undefined;let worldAdded=false;
  const nightBaselines=new Map<THREE.MeshStandardMaterial,{emissive:THREE.Color,intensity:number,map:THREE.Texture|null,kind:'window'|'sign'}>();
  function applyFacadeNight(night:boolean){
    if(!worldAdded)return;
    world.group.traverse(o=>{if(!(o instanceof THREE.Mesh))return;for(const m of Array.isArray(o.material)?o.material:[o.material]){if(!(m instanceof THREE.MeshStandardMaterial)||nightBaselines.has(m))continue;const windowMaterial=m.name.startsWith('architecture-glass')&&!m.name.includes('Apple');const sign=o.name.startsWith('Original text:');if(windowMaterial||sign)nightBaselines.set(m,{emissive:m.emissive.clone(),intensity:m.emissiveIntensity,map:m.emissiveMap,kind:sign?'sign':'window'});}});
    for(const [material,base]of nightBaselines){if(night){material.emissive.set(base.kind==='sign'?'#fff5dd':'#ffd5a0');material.emissiveIntensity=base.kind==='sign'?.85:material.name.includes('glassB')?.8:material.name.includes('glassC')?.28:.035;if(base.kind==='sign')material.emissiveMap=material.map;}else{material.emissive.copy(base.emissive);material.emissiveIntensity=base.intensity;material.emissiveMap=base.map;}material.needsUpdate=true;}
  }
  function lighting(value:string){if(!['day','warm','night'].includes(value))throw Error('Unknown lighting condition '+value);state.light=value;const warm=value==='warm',night=value==='night';document.body.classList.toggle('night',night);sun.position.set(warm?-130:-90,warm?58:145,warm?90:75);sun.color.set(night?'#b8cef5':warm?'#ffd7a1':'#fff5db');sun.intensity=night?.18:warm?3.4:3.3;hemi.intensity=night?.18:warm?1.35:1.6;hemi.color.set(night?'#809abe':'#cde7ff');hemi.groundColor.set(night?'#1b2632':'#8f897a');skyMaterial.uniforms.sunStrength.value=night?0:1;skyMaterial.uniforms.sunDirection.value.copy(sun.position).normalize();skyMaterial.uniforms.zenith.value.set(night?'#05111f':warm?'#7ea5c4':'#6aafe1');skyMaterial.uniforms.horizon.value.set(night?'#172532':warm?'#efd8bd':'#dce6e9');renderer.toneMappingExposure=night?1.35:warm?1.1:1.03;scene.fog=new THREE.Fog(night?'#101d2d':'#ccd9df',260,850);
    const w=256,h=128,data=new Float32Array(w*h*4);const zen=skyMaterial.uniforms.zenith.value as THREE.Color;const hor=skyMaterial.uniforms.horizon.value as THREE.Color;const ground=new THREE.Color(night?'#111820':'#8c8b80');for(let y=0;y<h;y++){const elevation=Math.cos(Math.PI*(y+.5)/h);const c=elevation>=0?hor.clone().lerp(zen,Math.pow(elevation,.45)):hor.clone().lerp(ground,Math.pow(-elevation,.25));for(let x=0;x<w;x++){const i=(y*w+x)*4;data[i]=c.r;data[i+1]=c.g;data[i+2]=c.b;data[i+3]=1;}}const map=new THREE.DataTexture(data,w,h,THREE.RGBAFormat,THREE.FloatType);map.mapping=THREE.EquirectangularReflectionMapping;map.needsUpdate=true;environment?.dispose();environment=pmrem.fromEquirectangular(map);map.dispose();scene.environment=environment.texture;scene.environmentIntensity=night?.4:.55;
    if(worldAdded){applyFacadeNight(night);world.setLighting?.(value);disposeArchitectureProbe?.();renderer.shadowMap.needsUpdate=true;const focusVisible=focusHighlight.visible;focusHighlight.visible=false;try{disposeArchitectureProbe=applyArchitectureProbe(scene,renderer);}finally{focusHighlight.visible=focusVisible;}}syncUI();}
  // Neutral current-frame owner. Its depth survives disabling GTAO.
  const depth=new THREE.DepthTexture(2,2,THREE.UnsignedIntType);depth.format=THREE.DepthFormat;
  const gbuffer=new THREE.WebGLRenderTarget(2,2,{type:THREE.HalfFloatType,minFilter:THREE.NearestFilter,magFilter:THREE.NearestFilter,depthTexture:depth});
  const normalMaterial=new THREE.MeshNormalMaterial();normalMaterial.side=THREE.DoubleSide;
  class GeometryPass extends Pass { constructor(){super();this.needsSwap=false;} render(r:THREE.WebGLRenderer){const old=scene.overrideMaterial;const bg=scene.background;const visible=sky.visible,focusVisible=focusHighlight.visible;sky.visible=false;focusHighlight.visible=false;scene.background=null;scene.overrideMaterial=normalMaterial;r.setRenderTarget(gbuffer);r.setClearColor(0x7777ff,1);r.clear();r.render(scene,camera);scene.overrideMaterial=old;scene.background=bg;sky.visible=visible;focusHighlight.visible=focusVisible;} setSize(w:number,h:number){gbuffer.setSize(w,h);} }
  const composer=new EffectComposer(renderer,new THREE.WebGLRenderTarget(2,2,{type:THREE.HalfFloatType}));
  const geometryPass=new GeometryPass();const beautyPass=new RenderPass(scene,camera);composer.addPass(geometryPass);composer.addPass(beautyPass);
  const gtao=new GTAOPass(scene,camera,2,2);
  // Same r185 denoising-noise algorithm, with an explicit original seed.
  // GTAOPass otherwise constructs SimplexNoise with Math.random on each reload.
  const denoiseSimplex=new SimplexNoise({random:rng('gtao-denoise-240514')});
  const noiseImage=gtao.pdNoiseTexture.image,noiseData=noiseImage.data;
  if(!noiseData||noiseImage.width!==64||noiseImage.height!==64)throw Error('Locked GTAO denoising-noise contract changed');
  for(let x=0;x<noiseImage.width;x++)for(let y=0;y<noiseImage.height;y++)for(let c=0;c<4;c++)noiseData[(x*noiseImage.height+y)*4+c]=(denoiseSimplex.noise(x+(c%2)*noiseImage.width,y+(c>1?noiseImage.height:0))*.5+.5)*255;
  gtao.pdNoiseTexture.needsUpdate=true;
  gtao.setGBuffer(depth);gtao.blendIntensity=.5;gtao.updateGtaoMaterial({radius:2.1,thickness:2.5,distanceExponent:1.8,distanceFallOff:1,scale:1,samples:16});gtao.updatePdMaterial({radius:4,samples:8});
  // Exact r185 reconstruction patch. Face against the full view vector, never N.z.
  const anchor='return normalize(cross(dpdx, dpdy));';
  for(const material of [gtao.gtaoMaterial,gtao.pdMaterial]){if(material.fragmentShader.split(anchor).length!==2)throw Error('Locked GTAO normal patch anchor changed');material.fragmentShader=material.fragmentShader.replace(anchor,`vec3 N = normalize(cross(dpdx, dpdy));\n#ifdef INCORRECT_Z_FACING\nreturn N.z < 0.0 ? -N : N;\n#else\nreturn dot(N, normalize(-ce)) < 0.0 ? -N : N;\n#endif`);material.needsUpdate=true;}
  composer.addPass(gtao);const normalDebug=new ShaderPass({uniforms:{tNormal:{value:null}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform sampler2D tNormal; varying vec2 vUv; void main(){gl_FragColor=texture2D(tNormal,vUv);}'});normalDebug.uniforms.tNormal.value=gbuffer.texture;composer.addPass(normalDebug);const output=new OutputPass();composer.addPass(output);const fxaa=new ShaderPass(FXAAShader);composer.addPass(fxaa);
  let linearCaptureRequested=false,linearCapture:Uint16Array|null=null;const passStats:Record<string,{calls:number,triangles:number,cpuMs:number}>={};for(const [name,pass] of [['geometry',geometryPass],['beauty',beautyPass],['gtao',gtao],['normalDebug',normalDebug],['output',output],['fxaa',fxaa]] as const){const original=pass.render.bind(pass) as (...args:any[])=>void;(pass as any).render=(...args:any[])=>{const calls=renderer.info.render.calls,triangles=renderer.info.render.triangles,start=performance.now();if(name==='output'&&linearCaptureRequested){const target=args[2] as THREE.WebGLRenderTarget;linearCapture=new Uint16Array(target.width*target.height*4);renderer.readRenderTargetPixels(target,0,0,target.width,target.height,linearCapture);linearCaptureRequested=false;}original(...args);passStats[name]={calls:renderer.info.render.calls-calls,triangles:renderer.info.render.triangles-triangles,cpuMs:performance.now()-start};};}
  let forcedSize:[number,number]|null=null;
  function resize(){const w=forcedSize?.[0]??innerWidth,h=forcedSize?.[1]??innerHeight;const ratio=forcedSize?1:Math.min(devicePixelRatio,state.quality==='high'?1.5:1);renderer.setPixelRatio(ratio);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();composer.setPixelRatio(ratio);composer.setSize(w,h);fxaa.material.uniforms.resolution.value.set(1/(w*ratio),1/(h*ratio));}
  window.addEventListener('resize',resize);resize();
  let world:World;let animationId=0;let tourTime=0;let tourStopIndex=-1;let tourBaseLight='day';let frames=0;let lastTime=performance.now();let lastHud=0;const samples:number[]=[];const renderSamples:number[]=[];const keys=new Set<string>();
  const euler=new THREE.Euler(0,0,0,'YXZ');let dragging=false;
  function setPose(position:number[],target:number[],mode:Mode='free'){state.seated=null;seatReturnPose=null;camera.position.fromArray(position);camera.lookAt(new THREE.Vector3().fromArray(target));state.mode=mode;if(mode!=='tour'){$('tour-transition').style.opacity='0';state.tourStop=null;}orbit.enabled=mode==='orbit';if(orbit.enabled){document.exitPointerLock();orbit.target.fromArray(target);orbit.update();}camera.updateMatrixWorld();}
  function setView(id:string){const v=cameras.find(v=>v.id===id);if(!v)throw Error(`Unknown camera ${id}`);state.view=id;const pos=[...v.position];if(world&&v.mode==='walk')pos[1]=world.groundHeight(pos[0],pos[2],pos[1]-1.7)+1.7;camera.fov=v.fov??55;camera.updateProjectionMatrix();setPose(pos,v.target,v.mode);syncUI();}
  function setMode(mode:Mode){if(!['walk','free','orbit','tour'].includes(mode))throw Error('Unknown camera mode '+mode);if(state.seated)standFromSeat();state.seated=null;seatReturnPose=null;state.mode=mode;if(mode!=='tour'){$('tour-transition').style.opacity='0';state.tourStop=null;}state.view=mode==='tour'?'tour':'roam';orbit.enabled=mode==='orbit';if(mode==='walk'&&world)camera.position.y=world.groundHeight(camera.position.x,camera.position.z,camera.position.y-1.7)+1.7;if(mode==='orbit'){document.exitPointerLock();keys.clear();orbit.target.set(0,7,0);if(camera.position.y<10)camera.position.set(83,95,76);orbit.update();}if(mode==='tour'){document.exitPointerLock();tourTime=0;tourStopIndex=-1;tourBaseLight=state.light;}syncUI();}
  function setDebug(debug:Debug){state.debug=debug;syncUI();}
  function setFeature(name:string,on:boolean){if(name!=='gtao')throw Error(`Unknown effect ${name}`);state.features.gtao=on;syncUI();}
  function quality(value:string){state.quality=value;sun.shadow.mapSize.setScalar(value==='high'?4096:2048);sun.shadow.map?.dispose();sun.shadow.map=null;gtao.updateGtaoMaterial({samples:value==='high'?16:8});resize();syncUI();}
  function setTime(seconds:number){if(!Number.isFinite(seconds)||seconds<0)throw Error('Animation time must be a finite non-negative number');state.time=seconds;tourTime=seconds;tourStopIndex=-1;if(world)world.update(seconds,0);}
  function reset(){world?.reset?.();state.selectedStore=null;$('store-card').hidden=true;state.frozen=false;state.features.gtao=true;state.debug='none';setTime(0);lighting('day');quality('high');setView('overview');}
  function syncUI(){if(!$('view'))return;($('view') as HTMLSelectElement).value=state.view;($('mode') as HTMLSelectElement).value=state.mode;($('light') as HTMLSelectElement).value=state.light;($('quality') as HTMLSelectElement).value=state.quality;($('debug') as HTMLSelectElement).value=state.debug;($('freeze') as HTMLInputElement).checked=state.frozen;($('ao') as HTMLInputElement).checked=state.features.gtao;$('view-state').textContent=`${state.view==='roam'?(state.mode==='orbit'?'Orbit exploration':'Free roam'):state.view==='tour'?`Tour · ${cameras.find(v=>v.id===state.tourStop)?.label??'Union Square'}`:cameras.find(v=>v.id===state.view)?.label??'Guided route'} · ${state.features.gtao&&state.debug==='none'&&state.light==='day'&&state.quality==='high'?'baseline light & quality':'custom settings'}`;}
  function showError(message:string){$('loading').hidden=false;document.querySelector('#loading strong')!.textContent='The square could not load';$('loading-detail').textContent=message;}
  function collision(x:number,z:number,feetY=camera.position.y-1.7){const r=.34;return world.colliders.some(c=>(!c.enabled||c.enabled())&&feetY+1.7>(c.minY??-Infinity)+.015&&feetY<(c.maxY??Infinity)-.015&&x+r>c.minX&&x-r<c.maxX&&z+r>c.minZ&&z-r<c.maxZ);}
  function standFromSeat(){if(seatReturnPose){camera.position.copy(seatReturnPose.position);camera.quaternion.copy(seatReturnPose.quaternion);}else camera.position.y=(seatFeetY??world.groundHeight(camera.position.x,camera.position.z,camera.position.y))+1.7;state.seated=null;seatFeetY=null;seatReturnPose=null;}
  function move(dx:number,dy:number,dz:number){if(state.seated)standFromSeat();if(state.mode==='walk'){const n=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.2));for(let i=0;i<n;i++){const feet=camera.position.y-1.7,nx=camera.position.x+dx/n,nz=camera.position.z+dz/n;if(!collision(nx,camera.position.z,feet))camera.position.x=nx;if(!collision(camera.position.x,nz,feet))camera.position.z=nz;camera.position.y=world.groundHeight(camera.position.x,camera.position.z,feet)+1.7;}}else if(state.mode==='free')camera.position.add(new THREE.Vector3(dx,dy,dz));camera.position.x=THREE.MathUtils.clamp(camera.position.x,-235,235);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-235,235);if(state.mode==='free')camera.position.y=THREE.MathUtils.clamp(camera.position.y,-20,240);state.view='roam';}
  const tourViews=['overview','monument','corner','nintendo-front','nintendo-ground','nintendo-lower','westin','apple-ground','apple-upper','detail','overview'];
  const tourDuration=60;
  function updateTour(dt:number){if(!state.frozen)tourTime+=dt;const stopSeconds=tourDuration/tourViews.length,phase=(tourTime%tourDuration)/stopSeconds,index=Math.floor(phase),within=phase-index;const view=cameras.find(v=>v.id===tourViews[index])!;
    if(index!==tourStopIndex){tourStopIndex=index;state.tourStop=view.id;const light=tourBaseLight==='night'?'night':index===tourViews.length-1?'warm':'day';if(light!==state.light)lighting(light);syncUI();}
    const position=[...view.position];if(view.mode==='walk')position[1]=world.groundHeight(position[0],position[2],position[1]-1.7)+1.7;
    // Absolute-time local dolly: a repeated setTime produces the identical pose.
    const progress=.5-.5*Math.cos(Math.PI*within);
    if(view.mode==='walk'){const dx=view.target[0]-position[0],dz=view.target[2]-position[2],length=Math.hypot(dx,dz),distance=.3*progress,feet=position[1]-1.7;let clear=length>.001;
      for(let travel=.05;clear&&travel<=distance+.05;travel+=.05){const step=Math.min(travel,distance),x=position[0]+dx/length*step,z=position[2]+dz/length*step;clear=!collision(x,z,feet)&&Math.abs(world.groundHeight(x,z,feet)-feet)<.12;}
      if(clear){position[0]+=dx/length*distance;position[2]+=dz/length*distance;position[1]=world.groundHeight(position[0],position[2],feet)+1.7;}
    }else{position[0]+=3*(progress-.5);}
    camera.position.fromArray(position);camera.lookAt(new THREE.Vector3().fromArray(view.target));camera.fov=view.fov??55;camera.updateProjectionMatrix();
    const fade=Math.max(0,1-within/.045,(within-.955)/.045);$('tour-transition').style.opacity=String(Math.min(1,fade));
  }
  function update(dt:number){if(!state.frozen){state.time+=dt;world.update(state.time,dt);}if(state.mode==='orbit'){orbit.update();}else if(state.mode==='tour'){updateTour(dt);}else if(keys.size&&(state.mode==='walk'||state.mode==='free')){const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')?12:3.2)*dt;const forward=new THREE.Vector3();camera.getWorldDirection(forward);if(state.mode==='walk'){forward.y=0;forward.normalize();}const right=new THREE.Vector3().crossVectors(forward,camera.up).normalize();const d=new THREE.Vector3();if(keys.has('KeyW')||keys.has('ArrowUp'))d.add(forward);if(keys.has('KeyS')||keys.has('ArrowDown'))d.sub(forward);if(keys.has('KeyD')||keys.has('ArrowRight'))d.add(right);if(keys.has('KeyA')||keys.has('ArrowLeft'))d.sub(right);if(state.mode==='free'){if(keys.has('KeyE'))d.y+=1;if(keys.has('KeyQ'))d.y-=1;}if(d.lengthSq()){d.normalize().multiplyScalar(speed);move(d.x,d.y,d.z);}}}
  function renderFrame(dt=0){if(state.disposed)return;const begin=performance.now();orbit.enabled=state.mode==='orbit';if(world)update(Math.min(dt,.1));camera.updateMatrixWorld();world?.updateViewer?.(camera.position);if(world&&state.status==='ready')updateFocus();renderer.shadowMap.needsUpdate=true;renderer.info.reset();gtao.enabled=state.features.gtao||state.debug!=='none';gtao.output=state.debug==='gtao'?GTAOPass.OUTPUT.Denoise:GTAOPass.OUTPUT.Default;normalDebug.enabled=state.debug==='normal';composer.render(dt);frames++;renderSamples.push(performance.now()-begin);if(renderSamples.length>12000)renderSamples.shift();}
  function animate(now:number){if(state.disposed)return;animationId=requestAnimationFrame(animate);const dt=Math.max(0,(now-lastTime)/1000);lastTime=now;if(state.status!=='ready')return;samples.push(dt*1000);if(samples.length>12000)samples.shift();try{renderFrame(dt);}catch(error){state.status='error';record('render',error);showError(String(error));cancelAnimationFrame(animationId);return;}if(now-lastHud>600){lastHud=now;const avg=samples.slice(-45).reduce((a,b)=>a+b,0)/Math.min(45,samples.length);$('performance').textContent=`${Math.round(1000/avg)} FPS · ${state.quality==='high'?'HIGH':'PERFORMANCE'}`;}}
  const onKey=(e:KeyboardEvent)=>{if(e.code==='Escape'){document.exitPointerLock();keys.clear();if(state.referenceOpen)closeReferenceViewer();return;}if(state.referenceOpen)return;if((e.target as HTMLElement)?.matches('select,input,button'))return;if(e.code==='KeyF'&&!e.repeat){e.preventDefault();interact();return;}if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){keys.add(e.code);e.preventDefault();if(state.mode==='tour')setMode('walk');}};window.addEventListener('keydown',onKey);window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());
  renderer.domElement.addEventListener('click',()=>{if(state.status==='ready'&&state.mode!=='orbit'&&!state.referenceOpen){if(state.mode==='tour')setMode('walk');renderer.domElement.requestPointerLock()?.catch(()=>{});}});
  renderer.domElement.addEventListener('pointerdown',()=>{dragging=state.mode!=='orbit';});window.addEventListener('pointerup',()=>dragging=false);
  document.addEventListener('pointerlockchange',()=>document.body.classList.toggle('locked',document.pointerLockElement===renderer.domElement));
  document.addEventListener('mousemove',e=>{if(state.status!=='ready'||state.mode==='tour'||state.mode==='orbit'||state.referenceOpen)return;if(document.pointerLockElement!==renderer.domElement&&!dragging)return;euler.setFromQuaternion(camera.quaternion);euler.y-=e.movementX*.002;euler.x=THREE.MathUtils.clamp(euler.x-e.movementY*.002,-1.5,1.5);camera.quaternion.setFromEuler(euler);state.view='roam';syncUI();});
  $('view').innerHTML=cameras.map(v=>`<option value="${v.id}">${v.label}</option>`).join('');
  $('view').addEventListener('change',e=>setView((e.target as HTMLSelectElement).value));$('mode').addEventListener('change',e=>setMode((e.target as HTMLSelectElement).value as Mode));$('light').addEventListener('change',e=>lighting((e.target as HTMLSelectElement).value));$('quality').addEventListener('change',e=>quality((e.target as HTMLSelectElement).value));$('debug').addEventListener('change',e=>setDebug((e.target as HTMLSelectElement).value as Debug));$('ao').addEventListener('change',e=>setFeature('gtao',(e.target as HTMLInputElement).checked));$('freeze').addEventListener('change',e=>{state.frozen=(e.target as HTMLInputElement).checked;});$('reset').addEventListener('click',reset);$('tour').addEventListener('click',()=>setMode(state.mode==='tour'?'walk':'tour'));$('collapse').addEventListener('click',()=>{const collapsed=!$('panel-body').hidden;$('panel-body').hidden=collapsed;$('collapse').textContent=collapsed?'+':'−';$('collapse').setAttribute('aria-expanded',String(!collapsed));$('collapse').setAttribute('aria-label',collapsed?'Expand controls':'Collapse controls');});
  let focusedTarget:InteractiveTarget|null=null,focusedStore:StoreRecord|null=null,seatFeetY:number|null=null,seatReturnPose:{position:THREE.Vector3,quaternion:THREE.Quaternion}|null=null,toastTimer:number|undefined;
  function toast(message:string){$('interaction-toast').textContent=message;$('interaction-toast').hidden=false;if(toastTimer)window.clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>$('interaction-toast').hidden=true,3500);}
  function selectStore(id:string){const record=world.stores?.find(store=>store.id===id);if(!record)return false;state.selectedStore=id;($('store') as HTMLSelectElement).value=id;$('store-card').hidden=false;$('store-name').textContent=record.name;$('store-category').textContent=record.category;$('store-address').textContent=record.address;$('store-status').textContent=`${record.status==='verified'?'Verified storefront':record.status==='closed'?'Closed / former storefront':'Occupancy uncertain'} · ${record.confidence}`;$('store-notes').textContent=record.notes;$('store-entry').textContent=record.interior?'Public interior modeled. Approach the entrance and use F where prompted.':'Exterior reconstruction; this storefront has no explorable interior.';const link=$<HTMLAnchorElement>('store-source');link.href=/^https?:\/\//.test(record.source)?record.source:'#';return true;}
  function populateStores(){const select=$<HTMLSelectElement>('store');select.replaceChildren(new Option('Choose a storefront…',''));for(const record of world.stores??[])select.add(new Option(record.name+(record.status==='uncertain'?' · uncertain':record.status==='closed'?' · former':''),record.id));}
  function updateFocus(){
    if(state.mode==='orbit'||state.mode==='tour'||state.referenceOpen){focusedTarget=null;focusedStore=null;state.focusedTarget=null;state.focusedStore=null;focusHighlight.visible=false;$('focus-hud').hidden=true;return;}
    const direction=camera.getWorldDirection(new THREE.Vector3());let score=-Infinity;focusedTarget=null;focusedStore=null;
    for(const target of world.targets??[]){if(target.object){let object:THREE.Object3D|null=target.object,visible=true;while(object){if(!object.visible)visible=false;object=object.parent;}if(!visible)continue;}const delta=target.position.clone().sub(camera.position),distance=delta.length();if(distance>target.radius)continue;const alignment=distance>.05?direction.dot(delta.multiplyScalar(1/distance)):1;if(alignment<.65&&distance>.7)continue;const candidate=alignment*2-distance/Math.max(target.radius,.1);if(candidate>score){score=candidate;focusedTarget=target;}}
    if(!focusedTarget)for(const store of world.stores??[]){const center=store.front.clone();center.y+=1.5;const delta=center.clone().sub(camera.position),distance=delta.length();if(distance>Math.max(12,store.width*.8))continue;const alignment=distance>.05?direction.dot(delta.multiplyScalar(1/distance)):1;if(alignment<.76)continue;const candidate=alignment*2-distance/30;if(candidate>score){score=candidate;focusedStore=store;}}
    state.focusedTarget=focusedTarget?.id??null;state.focusedStore=focusedStore?.id??null;const visible=Boolean(focusedTarget||focusedStore);$('focus-hud').hidden=!visible;focusHighlight.visible=visible&&state.debug==='none'&&!document.body.classList.contains('capture');if(!visible)return;
    if(focusedTarget){$('focus-title').textContent=focusedTarget.title;$('focus-category').textContent=focusedTarget.category;$('focus-description').textContent=focusedTarget.description();$('interact').innerHTML='<kbd>F</kbd> Interact';if(focusedTarget.object){focusBox.setFromObject(focusedTarget.object);if(focusBox.isEmpty()||focusBox.getSize(new THREE.Vector3()).length()>5)focusBox.setFromCenterAndSize(focusedTarget.position,new THREE.Vector3(.7,.7,.7));}else focusBox.setFromCenterAndSize(focusedTarget.position,new THREE.Vector3(.65,.65,.65));}
    else if(focusedStore){$('focus-title').textContent=focusedStore.name;$('focus-category').textContent=focusedStore.category;$('focus-description').textContent=focusedStore.address;$('interact').innerHTML='<kbd>F</kbd> Store details';focusBox.setFromCenterAndSize(focusedStore.front.clone().add(new THREE.Vector3(0,1.6,0)),new THREE.Vector3(.65,1.1,.65));}
    focusHighlight.updateMatrixWorld(true);
  }
  function interact(id?:string){updateFocus();const target=focusedTarget;if(id&&target?.id!==id)return false;if(target){try{target.action();const seat=target.object?.userData.seatPosition,look=target.object?.userData.seatLookAt;if(Array.isArray(seat)&&seat.length===3){if(state.seated===target.id){standFromSeat();}else{seatReturnPose={position:camera.position.clone(),quaternion:camera.quaternion.clone()};seatFeetY=world.groundHeight(seat[0],seat[2],seat[1]);camera.position.set(seat[0],seat[1]+.85,seat[2]);if(Array.isArray(look))camera.lookAt(new THREE.Vector3().fromArray(look));state.seated=target.id;state.mode='walk';state.view='roam';orbit.enabled=false;}}world.update(state.time,0);toast(state.seated?'Seated. Use WASD to stand and move.':target.description());syncUI();return true;}catch(error){record('interaction',error);toast('This interaction could not complete.');return false;}}if(focusedStore)return selectStore(focusedStore.id);return false;}
  $('interact').addEventListener('click',()=>interact());$('store').addEventListener('change',e=>selectStore((e.target as HTMLSelectElement).value));$('store-close').addEventListener('click',()=>{$('store-card').hidden=true;state.selectedStore=null;($('store') as HTMLSelectElement).value='';});

  interface ReferenceRow{id:string;title:string;viewId:string;imageUrl?:string;sourceUrl:string;date?:string;credit?:string;license?:string;notes?:string;matchConfidence?:string;light?:string}
  const referenceState={status:'closed',rows:[] as ReferenceRow[],selected:null as string|null,error:null as string|null};let referencePreviousFreeze=false;
  const developerMode=new URLSearchParams(location.search).has('dev');$('reference-open').hidden=!developerMode;
  function captureReferenceRender(){renderFrame();$<HTMLImageElement>('reference-render').src=renderer.domElement.toDataURL('image/png');}
  function selectReference(id:string){const row=referenceState.rows.find(r=>r.id===id);if(!row)return;referenceState.selected=id;($('reference-select') as HTMLSelectElement).value=id;const image=$<HTMLImageElement>('reference-image');image.hidden=true;image.removeAttribute('src');$('reference-empty').hidden=false;$('reference-empty').textContent=row.imageUrl?'Loading independent reference…':'This reference is linked for inspection at its source; no redistributable local photograph is included.';image.onload=()=>{image.hidden=false;$('reference-empty').hidden=true;};image.onerror=()=>{image.hidden=true;$('reference-empty').hidden=false;$('reference-empty').textContent='The source image could not be displayed. Open the cited source below.';};if(row.imageUrl&&(/^(https?:\/\/|\/)/.test(row.imageUrl)))image.src=row.imageUrl;const link=$<HTMLAnchorElement>('reference-source-link');link.href=/^https?:\/\//.test(row.sourceUrl)?row.sourceUrl:'#';link.textContent=row.title;$('reference-credit').textContent=[row.date,row.credit,row.license].filter(Boolean).join(' · ');$('reference-notes').textContent=`${row.matchConfidence??'Approximate context / direction match; not survey-calibrated.'} ${row.notes??''}`;if(cameras.some(v=>v.id===row.viewId))setView(row.viewId);state.frozen=true;setTime(0);if(row.light&&row.light!==state.light)lighting(row.light);syncUI();captureReferenceRender();}
  async function openReferenceViewer(){if(state.referenceOpen)return;referencePreviousFreeze=state.frozen;state.referenceOpen=true;state.frozen=true;document.exitPointerLock();keys.clear();$('reference-viewer').hidden=false;referenceState.status='loading';referenceState.error=null;try{if(!referenceState.rows.length){const response=await fetch('/references/comparison.json');if(!response.ok)throw Error(`Reference manifest returned ${response.status}`);const data=await response.json();const rows=Array.isArray(data)?data:data.references; if(!Array.isArray(rows))throw Error('Reference manifest must contain an array');referenceState.rows=rows;const select=$<HTMLSelectElement>('reference-select');select.replaceChildren();for(const row of referenceState.rows)select.add(new Option(row.title,row.id));}referenceState.status='ready';const matched=referenceState.rows.find(r=>r.viewId===state.view);if(referenceState.rows.length)selectReference(matched?.id??referenceState.rows[0].id);else{$('reference-empty').textContent='No independent reference rows are available.';captureReferenceRender();}}catch(error){referenceState.status='error';referenceState.error=String(error);$('reference-empty').hidden=false;$('reference-empty').textContent=String(error);captureReferenceRender();}syncUI();}
  function closeReferenceViewer(){if(!state.referenceOpen)return;state.referenceOpen=false;state.frozen=referencePreviousFreeze;referenceState.status='closed';$('reference-viewer').hidden=true;syncUI();}
  $('reference-open').addEventListener('click',()=>void openReferenceViewer());$('reference-close').addEventListener('click',closeReferenceViewer);$('reference-select').addEventListener('change',e=>selectReference((e.target as HTMLSelectElement).value));$('reference-capture').addEventListener('click',captureReferenceRender);$('reference-layout').addEventListener('change',e=>{$('reference-images').classList.toggle('overlay',(e.target as HTMLSelectElement).value==='overlay');});$('reference-opacity').addEventListener('input',e=>{$('reference-images').style.setProperty('--reference-opacity',String(Number((e.target as HTMLInputElement).value)/100));});
  function stats(){const geometrySet=new Set<THREE.BufferGeometry>(),materialSet=new Set<THREE.Material>(),textureSet=new Set<THREE.Texture>();let geometryBytes=0,textureBytes=0;scene.traverse(o=>{if(o instanceof THREE.Mesh){geometrySet.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){materialSet.add(m);for(const value of Object.values(m))if(value instanceof THREE.Texture)textureSet.add(value);}}});for(const g of geometrySet){for(const attr of Object.values(g.attributes))geometryBytes+=attr.array.byteLength;geometryBytes+=g.index?.array.byteLength??0;}for(const t of textureSet){const im=t.image as any;if(im?.width&&im?.height)textureBytes+=im.width*im.height*4*(t.type===THREE.FloatType?4:t.type===THREE.HalfFloatType?2:1)*(t.generateMipmaps?4/3:1);}const resourceEstimates={geometryBytes,materialCount:materialSet.size,textureBytes:Math.ceil(textureBytes),renderTargetBytes:gbuffer.width*gbuffer.height*(8+4+8*2+8*2)+sun.shadow.mapSize.x*sun.shadow.mapSize.y*8,method:'Typed-array geometry bytes; RGBA texture estimate with mip factors; half-float composer/AO/normal plus depth and shadow map estimate. Driver allocation and compressed/internal alignment are unavailable.'};const gl=renderer.getContext();const ext=gl.getExtension('WEBGL_debug_renderer_info');const sorted=[...samples].sort((a,b)=>a-b);const cpu=[...renderSamples].sort((a,b)=>a-b);const quant=(a:number[],q:number)=>a[Math.min(a.length-1,Math.floor(a.length*q))]??null;const size=renderer.getDrawingBufferSize(new THREE.Vector2());return{status:state.status,frames,passes:JSON.parse(JSON.stringify(passStats)),resourceEstimates,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,points:renderer.info.render.points,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,programs:renderer.info.programs?.length,frameMs:{median:quant(sorted,.5),p95:quant(sorted,.95),count:sorted.length},cpuRenderMs:{median:quant(cpu,.5),p95:quant(cpu,.95)},gpuTimer:{available:false,reason:'No asynchronous disjoint-timer query collector; wall timing is not GPU timing.'},renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),vendor:ext?gl.getParameter(ext.UNMASKED_VENDOR_WEBGL):gl.getParameter(gl.VENDOR),webgl:gl.getParameter(gl.VERSION),viewport:[innerWidth,innerHeight],drawingBuffer:[size.x,size.y],targets:{gbuffer:[gbuffer.width,gbuffer.height],gtao:[gtao.width,gtao.height],composer:[composer.readBuffer.width,composer.readBuffer.height]},dpr:renderer.getPixelRatio(),quality:state.quality,loadMs:readyMs,errors:[...errors]};}
  function readAO(){const data=new Uint16Array(gtao.width*gtao.height*4);renderer.readRenderTargetPixels(gtao.gtaoRenderTarget,0,0,gtao.width,gtao.height,data);return Array.from(data,THREE.DataUtils.fromHalfFloat);}
  function probeFacing(negative=false){for(const m of [gtao.gtaoMaterial,gtao.pdMaterial]){if(negative)m.defines.INCORRECT_Z_FACING=1;else delete m.defines.INCORRECT_Z_FACING;m.needsUpdate=true;}gtao.gtaoMaterial.defines.FRAGMENT_OUTPUT='vec4(vec3(dot(viewNormal, normalize(-viewPos)) * 0.5 + 0.5), 1.0)';gtao.gtaoMaterial.needsUpdate=true;renderFrame();const pixels=readAO();const values:number[]=[];for(let y=2;y<76;y++)for(let x=3;x<189;x++)values.push(pixels[(y*192+x)*4]*2-1);return{minimum:Math.min(...values),mean:values.reduce((a,b)=>a+b,0)/values.length,samples:values.length};}
  function runFacingFixture(){const saved={position:camera.position.clone(),quaternion:camera.quaternion.clone(),fov:camera.fov,state:JSON.parse(JSON.stringify(state)),fog:scene.fog};const visibility=scene.children.map(o=>[o,o.visible] as const);for(const [o]of visibility)o.visible=false;scene.fog=null;const plane=new THREE.Mesh(new THREE.PlaneGeometry(600,600),new THREE.MeshBasicMaterial({color:'white',side:THREE.DoubleSide}));plane.rotation.x=-Math.PI/2;scene.add(plane);state.mode='free';state.frozen=true;state.features.gtao=true;state.debug='gtao';camera.position.set(0,1.7,0);camera.rotation.set(.06,0,0,'YXZ');camera.fov=62;forcedSize=[192,192];resize();let result;try{const correct=probeFacing(false);const negative=probeFacing(true);for(const m of[gtao.gtaoMaterial,gtao.pdMaterial]){delete m.defines.INCORRECT_Z_FACING;m.needsUpdate=true;}delete gtao.gtaoMaterial.defines.FRAGMENT_OUTPUT;gtao.gtaoMaterial.needsUpdate=true;renderFrame();const pixels=readAO();const values:number[]=[];for(let y=2;y<76;y++)for(let x=3;x<189;x++)values.push(pixels[(y*192+x)*4]);const aoMean=values.reduce((a,b)=>a+b,0)/values.length;result={id:'gtao-normal-facing-2026-08-06',correct,negative,aoMean,pass:correct.minimum>0&&negative.minimum<0&&aoMean>.93,dimensions:stats().targets};}finally{scene.remove(plane);plane.geometry.dispose();(plane.material as THREE.Material).dispose();for(const [o,v]of visibility)o.visible=v;scene.fog=saved.fog;Object.assign(state,saved.state);camera.position.copy(saved.position);camera.quaternion.copy(saved.quaternion);camera.fov=saved.fov;forcedSize=null;resize();syncUI();renderFrame();}return result;}
  function runOcclusionFixtures(){
    const saved={position:camera.position.clone(),quaternion:camera.quaternion.clone(),fov:camera.fov,state:JSON.parse(JSON.stringify(state)),fog:scene.fog};const visibility=scene.children.map(o=>[o,o.visible] as const);for(const [o]of visibility)o.visible=false;scene.fog=null;const root=new THREE.Group();const mat=new THREE.MeshBasicMaterial({color:'white',side:THREE.DoubleSide});const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),mat);floor.rotation.x=-Math.PI/2;root.add(floor);const block=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),mat);block.position.y=.5;root.add(block);scene.add(root);state.mode='free';state.frozen=true;state.features.gtao=true;state.debug='gtao';camera.fov=62;forcedSize=[192,192];resize();const ray=new THREE.Raycaster();const sample=(name:string)=>{renderFrame();const data=readAO();root.updateMatrixWorld(true);const near:number[]=[],far:number[]=[],object:number[]=[];for(let y=3;y<189;y+=2)for(let x=3;x<189;x+=2){ray.setFromCamera(new THREE.Vector2((x+.5)/192*2-1,(y+.5)/192*2-1),camera);const hit=ray.intersectObjects(root.children)[0];if(!hit)continue;const ao=data[(y*192+x)*4];if(hit.object!==floor){object.push(ao);continue;}const r=Math.hypot(hit.point.x,hit.point.z);if(r<1.8)near.push(ao);if(r>4&&r<9)far.push(ao);}const summary=(a:number[])=>({count:a.length,mean:a.reduce((v,n)=>v+n,0)/Math.max(1,a.length),minimum:a.length?Math.min(...a):null});return{name,near:summary(near),far:summary(far),object:summary(object),radius:gtao.gtaoMaterial.uniforms.radius.value,camera:camera.position.toArray()};};let result;
    try{setPose([4,3,6],[0,.3,0]);const grounded=sample('object contact');block.position.y=2.5;const suspended=sample('suspended two metres');block.visible=false;const removed=sample('occluder removed');block.visible=true;block.position.set(-1,1.5,0);block.scale.set(.15,3,5);const wall=sample('vertical wall and depth discontinuity');const wall2=new THREE.Mesh(new THREE.BoxGeometry(5,3,.15),mat);wall2.position.set(1.5,1.5,-2);root.add(wall2);const corner=sample('inside corner');block.visible=false;wall2.visible=false;const underside=new THREE.Mesh(new THREE.BoxGeometry(4,.2,4),mat);underside.position.y=2.8;root.add(underside);setPose([.2,1.7,1],[0,2.8,-1]);const beneath=sample('underside');underside.visible=false;block.visible=true;block.position.set(0,.5,0);block.scale.set(1,1,1);setPose([4,3,6],[0,.3,0]);gtao.updateGtaoMaterial({radius:.5});const smallRadius=sample('radius half metre');gtao.updateGtaoMaterial({radius:3});const largeRadius=sample('radius three metres');result={cases:[grounded,suspended,removed,wall,corner,beneath,smallRadius,largeRadius],checks:{contactLocalized:grounded.near.mean<grounded.far.mean-.01,removalRaisesAO:removed.near.mean>grounded.near.mean+.01,heightChangesAO:Math.abs(suspended.near.mean-grounded.near.mean)>.01,unoccludedFloor:removed.near.mean>.93,radiusSensitivity:Math.abs(smallRadius.near.mean-largeRadius.near.mean)>.005,allFinite:[grounded,suspended,removed,wall,corner,beneath,smallRadius,largeRadius].every(v=>Number.isFinite(v.near.mean)&&Number.isFinite(v.object.mean))}};}
    finally{root.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});mat.dispose();scene.remove(root);gtao.updateGtaoMaterial({radius:2.1});for(const [o,v]of visibility)o.visible=v;scene.fog=saved.fog;Object.assign(state,saved.state);camera.position.copy(saved.position);camera.quaternion.copy(saved.quaternion);camera.fov=saved.fov;forcedSize=null;resize();syncUI();renderFrame();}return result;
  }
  function compareGTAO(){
    const saved={enabled:state.features.gtao,debug:state.debug,frozen:state.frozen,mode:state.mode};state.debug='none';state.frozen=true;state.mode='free';const capture=(on:boolean)=>{state.features.gtao=on;linearCaptureRequested=true;renderFrame();if(!linearCapture)throw Error('Linear HDR capture was not consumed by the displayed OutputPass');return linearCapture as Uint16Array;};let result;
    try{const a=capture(true),repeat=capture(true),b=capture(false);const size=renderer.getDrawingBufferSize(new THREE.Vector2());const w=size.x,h=size.y,pixels=w*h;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d')!;const bitmap=ctx.createImageData(w,h);let noise=0,reduction=0,affected=0,brightened=0;const tiles=Array.from({length:64},()=>({sum:0,pixels:0}));for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,display=((h-1-y)*w+x)*4;let d=0,n=0;for(let c=0;c<3;c++){const on=THREE.DataUtils.fromHalfFloat(a[i+c]),off=THREE.DataUtils.fromHalfFloat(b[i+c]);d+=(off-on)/3;n+=Math.abs(on-THREE.DataUtils.fromHalfFloat(repeat[i+c]))/3;bitmap.data[display+c]=Math.round(Math.min(1,Math.max(0,off-on)*6)*255);}bitmap.data[display+3]=255;noise+=n;reduction+=d;if(d>.0002)affected++;if(d<-.0002)brightened++;const tile=tiles[Math.min(7,Math.floor((h-1-y)/h*8))*8+Math.min(7,Math.floor(x/w*8))];tile.sum+=d;tile.pixels++;}ctx.putImageData(bitmap,0,0);result={view:state.view,width:w,height:h,colorContract:'Half-float linear HDR input to actual displayed OutputPass; before ACES and sRGB; GTAO on repeat versus off at identical frozen geometry/camera',noiseMean:noise/pixels,meanReduction:reduction/pixels,affectedFraction:affected/pixels,brightenedFraction:brightened/pixels,tiles:tiles.map(t=>t.sum/t.pixels),differencePng:canvas.toDataURL('image/png'),pass:reduction/pixels>noise/pixels+.00001&&affected/pixels>.002&&brightened/pixels<.0001};}
    finally{state.features.gtao=saved.enabled;state.debug=saved.debug;state.frozen=saved.frozen;state.mode=saved.mode;linearCapture=null;syncUI();renderFrame();}return result;
  }
  function runShadowOptimizationFixture(){const saved={frozen:state.frozen,mode:state.mode,automatic:renderer.shadowMap.autoUpdate};state.frozen=true;state.mode='free';const read=()=>{const size=renderer.getDrawingBufferSize(new THREE.Vector2()),pixels=new Uint8Array(size.x*size.y*4);renderer.getContext().readPixels(0,0,size.x,size.y,renderer.getContext().RGBA,renderer.getContext().UNSIGNED_BYTE,pixels);return pixels;};let result;try{renderer.shadowMap.autoUpdate=true;renderFrame();const before=read(),beforeStats=stats();renderer.shadowMap.autoUpdate=false;renderFrame();const after=read(),afterStats=stats();let maximum=0,sum=0,changed=0;for(let i=0;i<before.length;i++){const d=Math.abs(before[i]-after[i]);maximum=Math.max(maximum,d);sum+=d;if(d)changed++;}result={view:state.view,before:beforeStats,after:afterStats,maximumByteDifference:maximum,meanByteDifference:sum/before.length,changedChannels:changed,pass:maximum===0&&afterStats.drawCalls<beforeStats.drawCalls&&afterStats.triangles<beforeStats.triangles};}finally{state.frozen=saved.frozen;state.mode=saved.mode;renderer.shadowMap.autoUpdate=saved.automatic;renderFrame();}return result;}
  function dispose(){if(state.disposed)return;state.disposed=true;state.status='disposed';if(console.error===captureConsoleError)console.error=originalConsoleError;cancelAnimationFrame(animationId);window.removeEventListener('resize',resize);window.removeEventListener('keydown',onKey);orbit.dispose();keys.clear();const geometry=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>(),textures=new Set<THREE.Texture>();scene.traverse(o=>{const m=o as THREE.Mesh;if(m.geometry)geometry.add(m.geometry);for(const material of Array.isArray(m.material)?m.material:m.material?[m.material]:[]){materials.add(material);for(const v of Object.values(material))if(v instanceof THREE.Texture)textures.add(v);}});geometry.forEach(v=>v.dispose());materials.forEach(v=>v.dispose());textures.forEach(v=>v.dispose());disposeArchitectureProbe?.();environment?.dispose();pmrem.dispose();gbuffer.dispose();depth.dispose();normalMaterial.dispose();gtao.dispose();gtao.gtaoMaterial.dispose();gtao.blendMaterial.dispose();output.dispose();normalDebug.dispose();fxaa.dispose();composer.dispose();renderer.dispose();}
  let readyMs:number|null=null;const stageTimes:Record<string,number>={runtimeCreated:performance.now()-initialTime};const stage=(name:string)=>{state.stage=name;stageTimes[name]=performance.now()-initialTime;$('loading-detail').textContent=name;};
  const inspection={get ready(){return state.status==='ready';},state,stageTimes,errors,cameras,tour:{duration:tourDuration,views:tourViews},renderer,scene,camera,renderFrame,setView,setPose:(p:number[],t:number[],m:Mode='free')=>{setPose(p,t,m);state.view='roam';syncUI();},getPose:()=>({position:camera.position.toArray(),quaternion:camera.quaternion.toArray(),mode:state.mode,view:state.view}),setMode,setDebug,setFeature,setTime,interact,selectStore,openReferenceViewer,closeReferenceViewer,referenceState,targets:()=>world.targets?.map(t=>({id:t.id,title:t.title,category:t.category,position:t.position.toArray(),radius:t.radius,description:t.description(),objectUuid:t.object?.uuid,objectName:t.object?.name}))??[],stores:()=>world.stores??[],setLighting:lighting,setQuality:quality,freeze:(on=true)=>{state.frozen=on;syncUI();},stats,reset,dispose,runFacingFixture,runOcclusionFixtures,compareGTAO,runShadowOptimizationFixture,move:(x:number,y:number,z:number)=>move(x,y,z),groundHeight:(x:number,z:number,feetY?:number)=>world.groundHeight(x,z,feetY),collides:(x:number,z:number,feetY?:number)=>collision(x,z,feetY),colliders:()=>world.colliders.map(c=>({...c})),groundRaycast:(x:number,z:number,feetY?:number)=>{const y=world.groundHeight(x,z,feetY);const ray=new THREE.Raycaster(new THREE.Vector3(x,y+1.25,z),new THREE.Vector3(0,-1,0),0,3);const hit=ray.intersectObject(world.group,true).find(h=>h.face&&h.face.normal.y>.5);return hit?{y:hit.point.y,name:hit.object.name,expected:y,error:hit.point.y-y}:null;},capture:()=>{renderFrame();return renderer.domElement.toDataURL('image/png');},frameTimings:()=>({frame:[...samples],cpu:[...renderSamples]}),resetMeasurements:()=>{samples.length=0;renderSamples.length=0;},diagnostics:()=>({errors:[...errors],state:{...state},stats:stats()}),injectDiagnostic:(message:string)=>record('intentional-fixture',message),clearIntentionalDiagnostics:()=>{for(let i=errors.length-1;i>=0;i--)if(errors[i].kind==='intentional-fixture')errors.splice(i,1);}};
  (window as any).__scene=inspection;
  try{stage('Preparing lighting');lighting('day');stage('Building geometry and loading Blender meshes');world=await builder();scene.add(world.group);setTime(0);worldAdded=true;populateStores();applyFacadeNight(state.light==='night');world.setLighting?.(state.light);stage('Capturing facade reflections');renderer.shadowMap.needsUpdate=true;disposeArchitectureProbe=applyArchitectureProbe(scene,renderer);setView('overview');stage('Compiling materials and preparing the first view');await renderer.compileAsync(scene,camera);stage('Rendering the first frame');renderFrame();if(errors.some(e=>e.kind==='shader'))throw Error('Shader compilation failed; see retained diagnostics.');state.status='ready';stage('Ready');readyMs=performance.now()-initialTime;$('loading').hidden=true;lastTime=performance.now();animationId=requestAnimationFrame(animate);}catch(error){state.status='error';record('initialization',error);showError(String(error));throw error;}
  return inspection;
}
