// Pangyo stage-2 hero modules: the GLBs generated by tools/bpl/gen_pangyo.py, fitted to their OSM
// footprints, plus the procedural podium and the Three.js fallbacks.
//
// Which buildings get a hero module is data (`data/hero.json`); this file only registers the named
// builders and the placement maths they share:
//
//   * scale  — the module's manifest `footprint` [w, d] is scaled to the footprint's oriented
//              bounding box, and its manifest `height` to the building height, so a module is
//              authored at roughly its real size and the fit stays near 1.
//   * yaw    — the module's front (−Z, the bpl convention) is turned toward the street: the long
//              axis of the oriented bbox fixes the two candidate normals and the one nearer a
//              fitted street wins, unless the hero entry names a `facing` direction or a `yaw`.
//   * origin — the oriented bbox centre, sitting on the building's own base level (`baseY`).
//
// Collision is NOT this file's business: `World` keeps the massing collision polygon for hero
// buildings (only their geometry is replaced), so the walk controller and the studio's probe still
// see solid walls. See World.build().
import * as THREE from 'three';
import { Assets } from '../assets/Assets';
import { Materials } from '../materials/Library';
import { registerHeroModule } from './Hero';
import type { HeroContext } from './HeroContext';
import type { World, HeroEntry } from './World';
import type { App } from '../app/App';
import type { BuildingInfo } from './Buildings';
import { optionalData } from './World';
import type { P2 } from '../util/Geometry2D';
import type { StreetSpec } from './StreetGrid';

/** Minimum-area oriented bounding box of a footprint; `w` is always the longer side, along (ux, uz). */
export interface Obb { cx: number; cz: number; w: number; d: number; ux: number; uz: number }

export function orientedBox(fp: P2[]): Obb {
  let best: { area: number; w: number; d: number; ux: number; uz: number; cu: number; cv: number } | null = null;
  for (let i = 0; i < fp.length; i++) {
    const a = fp[i], b = fp[(i + 1) % fp.length];
    const dx = b[0] - a[0], dz = b[1] - a[1], len = Math.hypot(dx, dz);
    if (len < 1e-6) continue;
    const ux = dx / len, uz = dz / len;
    let minU = Infinity, maxU = -Infinity, minV = Infinity, maxV = -Infinity;
    for (const p of fp) {
      const u = p[0] * ux + p[1] * uz, v = -p[0] * uz + p[1] * ux;
      if (u < minU) minU = u; if (u > maxU) maxU = u;
      if (v < minV) minV = v; if (v > maxV) maxV = v;
    }
    const w = maxU - minU, d = maxV - minV, area = w * d;
    if (!best || area < best.area) best = { area, w, d, ux, uz, cu: (minU + maxU) / 2, cv: (minV + maxV) / 2 };
  }
  if (!best) return { cx: 0, cz: 0, w: 1, d: 1, ux: 1, uz: 0 };
  const cx = best.cu * best.ux - best.cv * best.uz;
  const cz = best.cu * best.uz + best.cv * best.ux;
  // orient so `w` is the longer side and (ux, uz) runs along it
  if (best.d > best.w) return { cx, cz, w: best.d, d: best.w, ux: -best.uz, uz: best.ux };
  return { cx, cz, w: best.w, d: best.d, ux: best.ux, uz: best.uz };
}

/** Perpendicular distance from (x, z) to a fitted street's centre line, or Infinity outside its run. */
function streetDistance(x: number, z: number, s: StreetSpec): number {
  const lo = Math.min(s.from, s.to), hi = Math.max(s.from, s.to);
  const along = s.axis === 'ns' ? z : x;
  if (along < lo - 20 || along > hi + 20) return Infinity;
  return Math.abs((s.axis === 'ns' ? x : z) - s.c);
}

/**
 * Yaw (radians) that turns the module's −Z front toward the street.
 *
 * The two candidates are the outward normals of the oriented bbox's long faces. An explicit
 * `entry.yaw` (degrees) wins outright; then an explicit `entry.facing` (a world direction the front
 * should point along); then the normal whose face is nearer a fitted street.
 */
export function fitYaw(obb: Obb, streets: StreetSpec[], entry?: Pick<HeroEntry, 'yaw' | 'facing'>): number {
  if (typeof entry?.yaw === 'number') return THREE.MathUtils.degToRad(entry.yaw);
  const cands: [number, number][] = [[obb.uz, -obb.ux], [-obb.uz, obb.ux]];
  let pick = cands[0];
  if (entry?.facing) {
    const [fx, fz] = entry.facing;
    pick = cands[0][0] * fx + cands[0][1] * fz >= cands[1][0] * fx + cands[1][1] * fz ? cands[0] : cands[1];
  } else {
    let bestD = Infinity;
    for (const n of cands) {
      const px = obb.cx + n[0] * (obb.d / 2 + 10), pz = obb.cz + n[1] * (obb.d / 2 + 10);
      let d = Infinity;
      for (const s of streets) d = Math.min(d, streetDistance(px, pz, s));
      if (d < bestD) { bestD = d; pick = n; }
    }
  }
  // yaw θ maps local −Z to (−sinθ, −cosθ); solve for the chosen normal
  return Math.atan2(-pick[0], -pick[1]);
}

/** Scale that fits a module authored at `nominal` (w, d, h) into the footprint bbox and height. */
export function fitScale(obb: Obb, height: number, nominal: { w: number; d: number; h: number }): THREE.Vector3 {
  return new THREE.Vector3(obb.w / Math.max(0.01, nominal.w), height / Math.max(0.01, nominal.h), obb.d / Math.max(0.01, nominal.d));
}

/** Nominal size of a module from its manifest entry (`footprint` + `height`), with a bbox fallback. */
function nominalOf(rel: string, fallback: { w: number; d: number; h: number }) {
  const m: any = Assets.manifest[rel];
  if (!m) return fallback;
  const bb = m.bbox_threejs;
  const w = Array.isArray(m.footprint) ? m.footprint[0] : (bb ? bb.max[0] - bb.min[0] : fallback.w);
  const d = Array.isArray(m.footprint) ? m.footprint[1] : (bb ? bb.max[2] - bb.min[2] : fallback.d);
  const h = typeof m.height === 'number' ? m.height : (bb ? bb.max[1] - bb.min[1] : fallback.h);
  return { w, d, h };
}

/**
 * Load a GLB module and place it on a building footprint. Returns false when the GLB is missing or
 * fails to parse, so the caller can fall back to procedural geometry (the world must boot either way).
 */
async function placeModule(ctx: HeroContext, rel: string, fallbackNominal: { w: number; d: number; h: number }): Promise<boolean> {
  const info = ctx.building;
  if (!info) { console.warn('[pangyo-hero] no building for', rel, ctx.entry.osmId); return false; }
  let model: THREE.Group;
  try { model = await Assets.instance(rel); } catch (e) { console.warn('[pangyo-hero] GLB unavailable, falling back', rel, e); return false; }
  const obb = orientedBox(info.footprint);
  const nominal = nominalOf(rel, fallbackNominal);
  model.name = rel;
  model.scale.copy(fitScale(obb, info.height, nominal));
  const holder = new THREE.Group();
  holder.name = `${rel}@${ctx.entry.osmId}`;
  holder.position.set(obb.cx, info.baseY, obb.cz);
  holder.rotation.y = fitYaw(obb, ctx.world.streetSpecs, ctx.entry);
  holder.add(model);
  ctx.group.add(holder);
  return true;
}

// ------------------------------------------------------------------ procedural fallback geometry

/** Wall quads around a footprint between two heights, each edge offset outward by `out` metres. */
function polyWalls(fp: P2[], y0: number, y1: number, out = 0): THREE.BufferGeometry {
  const pos: number[] = [], nrm: number[] = [], uv: number[] = [], idx: number[] = [];
  let u = 0;
  for (let i = 0; i < fp.length; i++) {
    const a = fp[i], b = fp[(i + 1) % fp.length];
    const len = Math.hypot(b[0] - a[0], b[1] - a[1]);
    if (len < 0.05) continue;
    const nx = (b[1] - a[1]) / len, nz = -(b[0] - a[0]) / len;
    const ax = a[0] + nx * out, az = a[1] + nz * out, bx = b[0] + nx * out, bz = b[1] + nz * out;
    const k = pos.length / 3;
    pos.push(ax, y0, az, bx, y0, bz, bx, y1, bz, ax, y1, az);
    uv.push(u, 0, u + len, 0, u + len, y1 - y0, u, y1 - y0);
    for (let q = 0; q < 4; q++) nrm.push(nx, 0, nz);
    idx.push(k, k + 2, k + 1, k, k + 3, k + 2);
    u += len;
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('normal', new THREE.Float32BufferAttribute(nrm, 3));
  g.setAttribute('uv', new THREE.Float32BufferAttribute(uv, 2));
  g.setIndex(idx);
  return g;
}

function polyRoof(fp: P2[], y: number): THREE.BufferGeometry {
  const g = new THREE.ShapeGeometry(new THREE.Shape(fp.map(([x, z]) => new THREE.Vector2(x, z))));
  g.rotateX(Math.PI / 2);
  const p = g.getAttribute('position') as THREE.BufferAttribute;
  for (let i = 0; i < p.count; i++) p.setY(i, y);
  g.computeVertexNormals();
  const n = g.getAttribute('normal') as THREE.BufferAttribute;
  if (n.getY(0) < 0) { const ix = g.getIndex()!; for (let i = 0; i < ix.count; i += 3) { const t = ix.getX(i + 1); ix.setX(i + 1, ix.getX(i + 2)); ix.setX(i + 2, t); } g.computeVertexNormals(); }
  return g;
}

function meshOf(geo: THREE.BufferGeometry, material: string, name: string): THREE.Mesh {
  const m = new THREE.Mesh(geo, Materials.get(material));
  m.name = name; m.castShadow = true; m.receiveShadow = true;
  return m;
}

interface WallMats { shaft: string; glass: string; rail: string; plinth: string }
const DARK_GLASS: WallMats = { shaft: 'glass_dark', glass: 'window_lit', rail: 'metal_black', plinth: 'granite_dark' };

/** A curtain-wall treatment on a footprint: shaft, per-floor vision band, rails, plinth, roof. */
function curtainWall(group: THREE.Group, fp: P2[], baseY: number, height: number, floorH: number, tag: string, mats: WallMats = DARK_GLASS) {
  const top = baseY + height;
  group.add(meshOf(polyWalls(fp, baseY, top), mats.shaft, `${tag}:shaft`));
  const floors = Math.max(1, Math.round(height / floorH));
  const vis: THREE.BufferGeometry[] = [], rails: THREE.BufferGeometry[] = [];
  for (let f = 1; f < floors; f++) {
    const y = baseY + f * floorH;
    if (y + floorH - 0.5 > top) break;
    vis.push(polyWalls(fp, y + 0.9, y + floorH - 0.5, 0.03));
    rails.push(polyWalls(fp, y + floorH - 0.62, y + floorH - 0.34, 0.12));
  }
  for (const g of vis) group.add(meshOf(g, mats.glass, `${tag}:glass`));
  for (const g of rails) group.add(meshOf(g, mats.rail, `${tag}:rail`));
  group.add(meshOf(polyWalls(fp, baseY, baseY + 0.5, 0.16), mats.plinth, `${tag}:plinth`));
  group.add(meshOf(polyRoof(fp, top), 'roof', `${tag}:roof`));
}

/** Canvas-drawn "NCSOFT" sign plane, used by the procedural fallback (the GLB has extruded text). */
function signPlane(width: number, height: number, text: string): THREE.Mesh {
  const c = document.createElement('canvas');
  c.width = 1024; c.height = Math.max(64, Math.round(1024 * height / width));
  const g = c.getContext('2d')!;
  g.fillStyle = '#0b0b0d'; g.fillRect(0, 0, c.width, c.height);
  g.fillStyle = '#ffffff'; g.textAlign = 'center'; g.textBaseline = 'middle';
  g.font = `bold ${Math.round(c.height * 0.72)}px sans-serif`;
  g.letterSpacing = `${Math.round(c.height * 0.14)}px`;
  g.fillText(text, c.width / 2, c.height / 2);
  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  const m = new THREE.Mesh(new THREE.PlaneGeometry(width, height),
    new THREE.MeshStandardMaterial({ map: tex, emissiveMap: tex, emissive: 0xffffff, emissiveIntensity: 0.45, roughness: 0.5, side: THREE.DoubleSide }));
  m.name = 'sign:NCSOFT';
  return m;
}

/** Procedural stand-in for pangyo/nc_rnd_center (used only if the GLB is missing). */
function proceduralNc(ctx: HeroContext, info: BuildingInfo) {
  const g = new THREE.Group(); g.name = 'pangyo/nc_rnd_center:procedural';
  curtainWall(g, info.footprint, info.baseY, info.height, 4.4, 'nc');
  const obb = orientedBox(info.footprint);
  const yaw = fitYaw(obb, ctx.world.streetSpecs, ctx.entry);
  // entrance: a 2-storey glass box on the front face
  const entry = new THREE.Mesh(new THREE.BoxGeometry(24, 8.6, 2.4), Materials.get('glass_clear'));
  entry.name = 'nc:entrance';
  const n = new THREE.Vector2(-Math.sin(yaw), -Math.cos(yaw));
  entry.position.set(obb.cx + n.x * (obb.d / 2), info.baseY + 4.3, obb.cz + n.y * (obb.d / 2));
  entry.rotation.y = yaw;
  g.add(entry);
  const sign = signPlane(24, 3, 'NCSOFT');
  sign.position.set(obb.cx + n.x * (obb.d / 2 - 3.2), info.baseY + info.height + 2.7, obb.cz + n.y * (obb.d / 2 - 3.2));
  sign.rotation.y = yaw + Math.PI;   // the plane's own front is +Z, the module convention is −Z
  g.add(sign);
  ctx.group.add(g);
}

/** Procedural stand-in for pangyo/alphadome_tower (used only if the GLB is missing). */
function proceduralTower(ctx: HeroContext, info: BuildingInfo, tag: string) {
  const g = new THREE.Group(); g.name = `${tag}:procedural`;
  curtainWall(g, info.footprint, info.baseY, info.height, 4.0, 'tower');
  ctx.group.add(g);
}

// ---------------------------------------------------------------------------- registered modules

registerHeroModule({
  id: 'pangyo/nc_rnd_center',
  async build(ctx) {
    if (!ctx.building) return;
    const ok = await placeModule(ctx, 'pangyo/nc_rnd_center', { w: 111.2, d: 40, h: 58 });
    if (!ok) proceduralNc(ctx, ctx.building);
    const obb = orientedBox(ctx.building.footprint);
    const yaw = fitYaw(obb, ctx.world.streetSpecs, ctx.entry);
    const n = new THREE.Vector2(-Math.sin(yaw), -Math.cos(yaw));
    ctx.registerStorefront({
      id: 'nc-lobby', name: 'NCSOFT R&D Center', category: 'office', address: ctx.building.address || '대왕판교로644번길 12',
      position: new THREE.Vector3(obb.cx + n.x * (obb.d / 2 + 6), ctx.building.baseY, obb.cz + n.y * (obb.d / 2 + 6)),
      facing: new THREE.Vector3(n.x, 0, n.y), width: 24, enterable: false, status: 'open', confidence: 'high',
    });
  },
});

registerHeroModule({
  id: 'pangyo/alphadome_tower',
  async build(ctx) {
    if (!ctx.building) return;
    const ok = await placeModule(ctx, 'pangyo/alphadome_tower', { w: 60, d: 60, h: 100 });
    if (!ok) proceduralTower(ctx, ctx.building, 'pangyo/alphadome_tower');
  },
});

/**
 * The NC podium (OSM way/694434544) is built straight on its own polygon rather than from a GLB
 * fitted to an oriented bbox: the podium is an L, its min-area bbox is 143.3 x 57.5 m for a 5,669 m²
 * footprint (69 % fill) and that box swallows three neighbouring OSM buildings (way/478539437 40 m,
 * way/478539439 32 m, way/694434546 48 m). Extruding the real footprint is both cheaper and right.
 */
registerHeroModule({
  id: 'pangyo/nc_podium',
  async build(ctx) {
    const info = ctx.building;
    if (!info) return;
    const g = new THREE.Group(); g.name = 'pangyo/nc_podium';
    // a light glazed podium rather than the tower's dark curtain wall: it is the plinth the tower
    // reads against, and a second black volume at street level just swallows the forecourt
    curtainWall(g, info.footprint, info.baseY, info.height, 4.2, 'podium',
      { shaft: 'window_lit', glass: 'glass_clear', rail: 'metal_alu', plinth: 'granite_grey' });
    g.add(meshOf(polyWalls(info.footprint, info.baseY + info.height, info.baseY + info.height + 0.9, 0.1), 'concrete_dark', 'podium:parapet'));
    g.add(meshOf(polyRoof(info.footprint, info.baseY + info.height + 0.9), 'roof', 'podium:cap'));
    ctx.group.add(g);
  },
});

// ------------------------------------------------------------------------------- hero props

/** One entry of the optional `data/hero_props.json`: a module with no OSM footprint to fit. */
export interface HeroProp { module: string; pos: [number, number]; yaw?: number; note?: string }

/**
 * Place the modules that have no building footprint (the 판교역 entrance canopies) from
 * `data/hero_props.json`. The group goes under `world` so the studio's `probePath` — which only
 * ray-casts the `world`, `props` and `vegetation` groups — sees them.
 */
export async function buildHeroProps(world: World, app: App): Promise<THREE.Group> {
  const group = new THREE.Group();
  group.name = 'hero_props';
  world.group.add(group);
  const list = await optionalData<HeroProp[]>('hero_props.json', 'hero props');
  if (!Array.isArray(list) || !list.length) return group;
  for (const p of list) {
    if (!p?.module || !Array.isArray(p.pos)) continue;
    const [x, z] = p.pos;
    const y = world.collision.terrain ? world.collision.terrain(x, z) : world.terrain.heightAt(x, z);
    try {
      const m = await Assets.instance(p.module);
      m.name = p.module;
      m.position.set(x, y - 0.05, z);
      m.rotation.y = THREE.MathUtils.degToRad(p.yaw ?? 0);
      group.add(m);
    } catch (e) {
      // fallback: a plain glass-and-steel canopy box so the world still boots without the GLB
      console.warn('[pangyo-hero] hero prop GLB unavailable, falling back', p.module, e);
      const g = new THREE.Group(); g.name = `${p.module}:procedural`;
      const roof = new THREE.Mesh(new THREE.BoxGeometry(18, 0.3, 8), Materials.get('glass_clear'));
      roof.position.y = 6; g.add(roof);
      for (const sx of [-1, 1]) for (const sz of [-1, 1]) {
        const c = new THREE.Mesh(new THREE.CylinderGeometry(0.2, 0.2, 6, 10), Materials.get('steel'));
        c.position.set(sx * 7.8, 3, sz * 2.9); g.add(c);
      }
      g.position.set(x, y - 0.05, z);
      g.rotation.y = THREE.MathUtils.degToRad(p.yaw ?? 0);
      group.add(g);
    }
  }
  void app;
  return group;
}
