import * as THREE from 'three';
import { streetHeight } from '../site';
import type { StoreRecord } from './types';

/** Supplemental census: July–August 2025. Architectural positions are authored estimates. */
function record(id:string,name:string,address:string,category:string,status:StoreRecord['status'],source:string,x:number,z:number,width:number,normal:[number,number,number],notes:string,confidence='Medium: current primary locator; summer2025 continuity inferred',interior?:string):StoreRecord {
  return {id,name,address,category,status,source,confidence,front:new THREE.Vector3(x,streetHeight(x,z)+1.55,z),normal:new THREE.Vector3(...normal),width,interior,notes};
}
export const stores:StoreRecord[] = [
  record('nintendo','Nintendo SAN FRANCISCO','331 Powell Street','Games and merchandise','verified','https://www.nintendo.com/us/whatsnew/nintendo-san-francisco-opens-its-doors-to-bring-smiles-to-guests-of-all-ages-near-and-far/',-85,32,24,[1,0,0],'Opened May 15, 2025. Public entry on Powell; modeled ground and lower sales floors.','High: dated official opening','nintendo'),
  record('apple','Apple Union Square','300 Post Street','Technology','verified','https://www.apple.com/retail/unionsquare/',44.1,-64,32,[0,0,1],'Official flagship location. Original interpreted interior with upper level and rear court.','High: official location and architectural documentation','apple'),
  record('westin','The Westin St. Francis','335 Powell Street','Hotel','verified','https://www.marriott.com/en-us/hotels/sfouw-the-westin-st-francis-san-francisco-on-union-square/overview/',-85,0,40,[1,0,0],'Historic hotel frontage. Nintendo occupies its southern retail corner; no hotel-room interior is modeled.'),
  record('saks-former','Former Saks Fifth Avenue','384 Post Street','Former department store','closed','https://www.ktvu.com/news/saks-fifth-leaving-san-francisco',-31.5,-64,28,[0,0,1],'Company announced closure May 10, 2025. Historical exterior lettering retained; exact removal date unverified.','High: dated company statement reported by KTVU'),
  record('tiffany','Tiffany & Co.','350 Post Street','Jewelry','verified','https://www.tiffany.com/stores/directory/united-states',-4.6,-64,23,[0,0,1],'Longstanding Post Street flagship; 2025 occupancy inferred between documented older and current operation.'),
  record('williams-sonoma','Williams Sonoma','340 Post Street','Kitchenware and home goods','verified','https://www.sfchronicle.com/realestate/article/union-square-building-sale-21086701.php',14.9,-64,14.2,[0,0,1],'The earlier model label Goyard was a factual error, not an era change. Contemporary 2025 reporting confirms Williams Sonoma remained; proposed Chanel succession occurred later.','High: 2013 Planning identity plus 2025 reporting'),
  record('macys',"Macy’s Union Square","170 O’Farrell Street; Geary frontage",'Department store','verified','https://www.macys.com/stores/ca/sanfrancisco/union-square_428.html',0,64,90,[0,0,-1],'The modeled frontage faces Geary; the official postal address is on O’Farrell. Closure plans do not imply a closed summer-2025 store.'),
  record('louis-vuitton','Louis Vuitton','233 Geary Street','Fashion and leather goods','verified','https://us.louisvuitton.com/eng-us/point-of-sale/usa/louis-vuitton-san-francisco-union-square',46.5,64,13,[0,0,-1],'Verified real address; exact modeled bay relative to Macy’s requires additional geospatial calibration.','Medium: official address; modeled frontage position approximate'),
  record('cheesecake-factory','The Cheesecake Factory','251 Geary Street','Restaurant','verified','https://locations.thecheesecakefactory.com/ca/san-francisco-34.html',19,64,10,[0,0,-1],'Located atop Macy’s. Selection marker represents exterior visibility; no direct street-level restaurant entrance or interior is claimed.'),
  record('neiman-marcus','Neiman Marcus','150 Stockton Street','Department store','verified','https://stores.neimanmarcus.com/stores/sanfrancisco/ca/sanfrancisco/1012',107,64,29,[0,0,-1],'Southeast diagonal context across Geary, not the plaza-facing 200 Stockton building.'),
  record('grand-hyatt','Grand Hyatt San Francisco','345 Stockton Street','Hotel','verified','https://www.hyatt.com/grand-hyatt/en-US/sfous-grand-hyatt-san-francisco',66,-96,24,[1,0,0],'Background tower behind Apple. Modeled side selection point is approximate, not an authenticated entrance.'),
  record('west-cafe','b. Patisserie','350 Powell Street · west plaza kiosk','Bakery and cafe','verified','https://www.sfrecpark.org/m/newsflash/home/detail/2127',-46.4,8,12,[1,0,0],'Replaced Miller & Lux in March 2025; active west kiosk in the selected summer era.','High: dated municipal announcement and June2025 lease record'),
  record('east-cafe','East plaza cafe · vacant','Stockton Street · east plaza kiosk','Vacant cafe','closed','https://sfrecpark.org/DocumentCenter/View/26253/Union-Square-East-Cafe-RFP-2025',46.4,-8,12,[-1,0,0],'June26,2025 municipal RFP explicitly records vacancy. Physical renovation was scheduled for fall/winter; Super Duper is a later tenant.','High: contemporary municipal RFP'),
  record('one-union-square','One Union Square · former Bulgari','200–212 Stockton Street','Retail frontage · occupancy unresolved','uncertain','https://www.bulgari.com/en-int/storelocator/united-states/california/san-francisco/200-stockton-street',85,30,28,[-1,0,0],'Bulgari relocated to206Grant inApril2025. Replacement tenant and exact old-sign removal date unverified; no active brand is invented.','High: relocation; low: replacement occupancy'),
  record('stockton-275-post','Post / Stockton corner retail','275–299 Post Street','Retail frontage · occupancy unresolved','uncertain','https://commissions.sfplanning.org/hpcpackets/2013.0628EH%20ARC.pdf',85,-37,14,[-1,0,0],'Historic parcel and facade supported by municipal photos. Summer2025 ground-floor business census incomplete.','Low: current occupancy unresolved'),
  record('stockton-250','250–260 Stockton frontage','250–260 Stockton Street','Retail frontage · occupancy unresolved','uncertain','https://commissions.sfplanning.org/hpcpackets/2013.0628EH%20ARC.pdf',85,-25,10,[-1,0,0],'Narrow gray historic facade. Business identity deliberately neutral pending dated verification.','Low: current occupancy unresolved'),
  record('stockton-234','234–240 Stockton frontage','234–240 Stockton Street','Retail frontage · occupancy unresolved','uncertain','https://commissions.sfplanning.org/hpcpackets/2013.0628EH%20ARC.pdf',85,-12,16,[-1,0,0],'Tall cream/green frontage north of Maiden Lane. No unsupported luxury label is assigned.','Low: current occupancy unresolved'),
  record('stockton-218','218–222 Stockton frontage','218–222 Stockton Street','Retail frontage · occupancy unresolved','uncertain','https://commissions.sfplanning.org/hpcpackets/2013.0628EH%20ARC.pdf',85,10,12,[-1,0,0],'Red brick corner south of Maiden Lane; contemporary tenant unresolved.','Low: current occupancy unresolved'),
  record('post-powell-retail','Post / Powell retail frontage','Post Street west of384Post','Retail frontage · occupancy unresolved','uncertain','https://media.bizj.us/view/img/12620914/chottomatte-3.jpg',-56,-64,20,[0,0,1],'Approximate ornate low frontage. Neither exact street address nor summer2025 tenant is established.','Low: address and occupancy unresolved'),
];

export const GEO_REFERENCE = {
  latitude:37.78799, longitude:-122.40750, gridEastBearingDegrees:80.87,
  rotationSource:'https://data.sfgov.org/Geographic-Locations-and-Boundaries/Street-Intersections/gmfx-8h6i',
  horizontalDatum:'WGS84 approximate monument center', verticalDatum:'Local authored Y; absolute geodetic elevation unknown',
  accuracy:'Interpretive georeferencing, not survey. Grid rotation approx9.13degrees; authored site has5–8percent horizontal uncertainty.'
} as const;
const R=6378137, DEG=Math.PI/180, angle=(90-GEO_REFERENCE.gridEastBearingDegrees)*DEG, c=Math.cos(angle), s=Math.sin(angle);
/** Grid +X is approx9.13degrees north of true east; +Z points approx9.13degrees east of true south. Y is retained as a local height. */
export function worldToGeo(x:number,z:number,y=2.4){const east=x*c+z*s,north=x*s-z*c;return{latitude:GEO_REFERENCE.latitude+north/R/DEG,longitude:GEO_REFERENCE.longitude+east/(R*Math.cos(GEO_REFERENCE.latitude*DEG))/DEG,localHeight:y};}
export function geoToWorld(latitude:number,longitude:number,localHeight=2.4){const east=(longitude-GEO_REFERENCE.longitude)*DEG*R*Math.cos(GEO_REFERENCE.latitude*DEG),north=(latitude-GEO_REFERENCE.latitude)*DEG*R;return new THREE.Vector3(east*c+north*s,localHeight,east*s-north*c);}
