import * as THREE from 'three';
export interface Collider {minX:number;maxX:number;minZ:number;maxZ:number;minY?:number;maxY?:number;enabled?:()=>boolean;name?:string}
export interface WalkSurface {id:string;contains:(x:number,z:number)=>boolean;height:(x:number,z:number)=>number}
export interface InteractiveTarget {id:string;title:string;category:string;position:THREE.Vector3;radius:number;action:()=>void;description:()=>string;object?:THREE.Object3D}
export interface Interior {id:string;group:THREE.Group;floors:WalkSurface[];colliders:Collider[];targets:InteractiveTarget[];entry:THREE.Vector3;update:(time:number,dt:number)=>void;reset:()=>void;setLighting?:(mode:string)=>void;bounds:THREE.Box3}
export interface StoreRecord {id:string;name:string;address:string;category:string;status:'verified'|'uncertain'|'closed';source:string;confidence:string;front:THREE.Vector3;normal:THREE.Vector3;width:number;interior?:string;notes:string}
export interface Frame {x:number;y:number;z:number;yaw:number}
export function point(frame:Frame,x:number,y:number,z:number){return new THREE.Vector3(frame.x+x*Math.cos(frame.yaw)+z*Math.sin(frame.yaw),frame.y+y,frame.z-x*Math.sin(frame.yaw)+z*Math.cos(frame.yaw));}
export function local(frame:Frame,x:number,z:number){const dx=x-frame.x,dz=z-frame.z;return{x:dx*Math.cos(frame.yaw)-dz*Math.sin(frame.yaw),z:dx*Math.sin(frame.yaw)+dz*Math.cos(frame.yaw)};}
export function rectCollider(frame:Frame,name:string,x:number,z:number,w:number,d:number,minY:number,maxY:number):Collider {const corners=[point(frame,x-w/2,0,z-d/2),point(frame,x+w/2,0,z-d/2),point(frame,x-w/2,0,z+d/2),point(frame,x+w/2,0,z+d/2)];return{name,minX:Math.min(...corners.map(p=>p.x)),maxX:Math.max(...corners.map(p=>p.x)),minZ:Math.min(...corners.map(p=>p.z)),maxZ:Math.max(...corners.map(p=>p.z)),minY:frame.y+minY,maxY:frame.y+maxY};}
export function rectFloor(frame:Frame,id:string,x:number,z:number,w:number,d:number,y:number,holes:Array<{x:number;z:number;w:number;d:number}>=[]):WalkSurface{return{id,contains:(wx,wz)=>{const p=local(frame,wx,wz);return Math.abs(p.x-x)<=w/2+.015&&Math.abs(p.z-z)<=d/2+.015&&!holes.some(h=>Math.abs(p.x-h.x)<h.w/2&&Math.abs(p.z-h.z)<h.d/2);},height:()=>frame.y+y};}
export function stairFloor(frame:Frame,id:string,x:number,zStart:number,zEnd:number,width:number,yStart:number,yEnd:number,steps:number):WalkSurface{return{id,contains:(wx,wz)=>{const p=local(frame,wx,wz);return Math.abs(p.x-x)<=width/2&&p.z>=Math.min(zStart,zEnd)&&p.z<=Math.max(zStart,zEnd);},height:(wx,wz)=>{const p=local(frame,wx,wz),t=THREE.MathUtils.clamp((p.z-zStart)/(zEnd-zStart),0,1);return frame.y+yStart+Math.min(steps,Math.floor(t*steps))*(yEnd-yStart)/steps;}};}
