/**
 * geo.ts — local coordinate frame for the Pangyo Techno Valley (판교테크노밸리, Seongnam) digital twin.
 *
 * GENERATED by tools/geo/build_gis.mjs — edit that script, not this file.
 * No dependencies. Mirrors the math in tools/geo/build_gis.mjs (which generates src/data/recon/gis.json).
 *
 * FRAME (right-handed, Three.js convention, metres):
 *   x = "grid-east"  : along the E–W arterials (판교로, 대왕판교로606번길), true bearing GRID_BEARING_DEG
 *   y = up           : metres above the origin ground elevation (ORIGIN_ELEVATION_M), so y = 0 at the origin
 *   z = "grid-south" : along the N–S arterials (판교역로, 대왕판교로, 분당내곡로), true bearing GRID_BEARING_DEG + 90
 *   Grid-north is therefore -z (true bearing -5.459).
 *
 * ORIGIN: area centroid of the NCSOFT R&D Center footprint, OSM way 694434545
 *   (엔씨소프트R&D센터, building:levels 12, height 58 m).
 *
 * GRID BEARING: length-weighted quadrupled-angle mean of every named `highway` segment inside the bbox
 *   (quadrupling folds both grid axes onto one estimate). Fitted from 567 segments /
 *   19356 m of roadway; the grid is rotated 5.459 deg counter-clockwise from true north.
 *
 * PROJECTION: equirectangular about LAT0 = 37.4 deg. Metres per degree from the standard WGS84 series
 *   (Snyder / NGS): M_PER_DEG_LAT = 111132.954 - 559.822 cos(2 phi) + 1.175 cos(4 phi) = 110985.161
 *                   M_PER_DEG_LON = 111412.84 cos(phi) - 93.5 cos(3 phi) + 0.118 cos(5 phi) = 88543.200
 *
 * ELEVATION: ORIGIN_ELEVATION_M is the OpenTopoData srtm30m value at the origin (metres above the EGM96 geoid).
 *
 * OSM data © OpenStreetMap contributors (ODbL). SRTM elevation is public domain.
 */

export const ORIGIN_LAT = 37.399371;
export const ORIGIN_LON = 127.108722;
/** Ground elevation at ORIGIN, metres (OpenTopoData srtm30m). y = 0 here. */
export const ORIGIN_ELEVATION_M = 37;
/** True bearing (deg clockwise from north) of the local +x axis (grid-east). */
export const GRID_BEARING_DEG = 84.541;
/** True bearing of grid-north (local -z). */
export const GRID_NORTH_BEARING_DEG = GRID_BEARING_DEG - 90;

export const LAT0_DEG = 37.4;
export const M_PER_DEG_LAT = 110985.161;
export const M_PER_DEG_LON = 88543.2;

/** WGS84 bounding box of the reconnaissance dataset. */
export const BBOX_WGS84 = { south: 37.395, west: 127.099, north: 37.4065, east: 127.117 } as const;

const D2R = Math.PI / 180;
const SIN_B = Math.sin(GRID_BEARING_DEG * D2R);
const COS_B = Math.cos(GRID_BEARING_DEG * D2R);

export interface LocalXYZ { x: number; y: number; z: number }
export interface GeoLatLon { lat: number; lon: number }

/**
 * WGS84 (lat, lon[, elevation m]) -> local frame.
 * If `elev` is omitted, y = 0.
 */
export function geoToLocal(lat: number, lon: number, elev?: number): LocalXYZ {
  const dE = (lon - ORIGIN_LON) * M_PER_DEG_LON; // metres true-east of origin
  const dN = (lat - ORIGIN_LAT) * M_PER_DEG_LAT; // metres true-north of origin
  // grid-east unit vector in (E, N) is (sin B, cos B); grid-north unit vector is (-cos B, sin B)
  const x = dE * SIN_B + dN * COS_B;
  const gridNorth = -dE * COS_B + dN * SIN_B;
  const y = elev === undefined ? 0 : elev - ORIGIN_ELEVATION_M;
  return { x, y, z: -gridNorth };
}

/** Local (x, z) -> WGS84 (lat, lon). Inverse of geoToLocal (ignores y). */
export function localToGeo(x: number, z: number): GeoLatLon {
  const gridNorth = -z;
  const dE = x * SIN_B - gridNorth * COS_B;
  const dN = x * COS_B + gridNorth * SIN_B;
  return { lat: ORIGIN_LAT + dN / M_PER_DEG_LAT, lon: ORIGIN_LON + dE / M_PER_DEG_LON };
}

/** Absolute elevation (m) -> local y. */
export const elevToLocalY = (elevM: number): number => elevM - ORIGIN_ELEVATION_M;
/** Alias kept for parity with union-square-sf's geo.ts. */
export const elevToY = elevToLocalY;
/** Local y -> absolute elevation (m). */
export const yToElev = (y: number): number => y + ORIGIN_ELEVATION_M;

/**
 * Rotate a true-north bearing (deg CW from north) into a local heading:
 * returns the angle in radians measured from +x toward +z (i.e. clockwise when viewed from above).
 */
export function bearingToLocalRad(bearingDeg: number): number {
  return (bearingDeg - GRID_BEARING_DEG) * D2R;
}

/** Local bounding box of BBOX_WGS84 (axis-aligned in the local frame, so slightly larger than the rotated bbox). */
export function localBbox(): { minX: number; maxX: number; minZ: number; maxZ: number } {
  const c = [
    geoToLocal(BBOX_WGS84.south, BBOX_WGS84.west), geoToLocal(BBOX_WGS84.south, BBOX_WGS84.east),
    geoToLocal(BBOX_WGS84.north, BBOX_WGS84.west), geoToLocal(BBOX_WGS84.north, BBOX_WGS84.east),
  ];
  return {
    minX: Math.min(...c.map((p) => p.x)), maxX: Math.max(...c.map((p) => p.x)),
    minZ: Math.min(...c.map((p) => p.z)), maxZ: Math.max(...c.map((p) => p.z)),
  };
}
